language: rust
rust:
  - stable
cache: cargo
before_script:
  - sudo apt-get install -y libssl-dev pkg-config
  - rustup component add rustfmt
script:
  - ./scripts/check.sh
  - cargo fmt -- --check
  # - docker build -t bwt .
