language: rust
rust:
  - stable
cache: cargo
before_script:
  - ./scripts/travis-deps.sh
script:
  - export PATH=/opt/bin:$PATH
  - cargo fmt -- --check
  - ./scripts/check.sh
  - cargo clippy --all-targets --all-features
  - VERBOSE=1 ./test/tests.sh
  # - docker build -t bwt .
