language: rust
rust:
  - stable
cache: cargo
before_script:
  - ./scripts/ci-deps.sh
  - export PATH=/opt/bin:$PATH
script:
  - cargo fmt -- --check
  - ./scripts/check.sh
  - cargo clippy --all-targets --all-features
  - ./test/tests.sh
