language: rust
rust:
  - stable
cache: cargo
before_script:
  - ./scripts/ci-deps.sh
  - export PATH=/opt/bin:$PATH
script:
  - cargo fmt -- --check
  - ./scripts/check.sh
  - cargo clippy --all-targets --all-features
  - ./test/tests.sh

  # Report reproducible builds shasums
  - >
    docker build -t bwt-builder -f scripts/builder.Dockerfile . &&
    docker run -v `pwd`:/usr/src/bwt bwt-builder &&
    docker build -t bwt-builder-osx -f scripts/builder-osx.Dockerfile . &&
    docker run -v `pwd`:/usr/src/bwt bwt-builder-osx &&
    echo '-----BEGIN SHA256SUM-----' &&
    (cd dist && sha256sum *) | sort &&
    echo ''
