[package]
name = "pxt"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[features]
default = [ "electrum", "http", "track-spends" ]
electrum = []
http = [ "warp", "tokio", "async-std" ]
track-spends = []

[dependencies]
bitcoin = "0.23.0"
bitcoincore-rpc = { version = "0.10.0" }
bitcoin_hashes = { version = "0.7.6", features = [ "serde" ] }
chrono = "0.4.11"
dirs = "2.0.2"
secp256k1 = "0.17.2"
hex = "0.4.2"
serde = { version = "1.0.106", features = [ "derive" ] }
serde_json = "1.0.52"
serde_derive = "1.0.106"
lazy_static = "1.4.0"
failure = "0.1.8"
log = "0.4.8"
stderrlog = "0.4.3"
structopt = "0.3.13"

tokio = { version = "0.2.20", features = ["macros"], optional = true }
warp = { version = "0.2.2", optional = true }
async-std = { version = "1.5.0", optional = true }
