[package]
name = "bwt"
version = "0.1.4"
description = "a lightweight hd wallet tracker and query engine for Bitcoin"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/shesek/bwt"
repository = "https://github.com/shesek/bwt"
keywords = [ "bitcoin", "electrum-server", "hd-wallet", "bitcoin-api", "xpub" ]
edition = "2018"
include = [ "src", "LICENSE" ]

[features]
default = [ "electrum", "http", "track-spends" ]
electrum = []
http = [ "warp", "tokio", "async-std" ]
webhooks = [ "reqwest" ]
track-spends = []

[dependencies]
bitcoin = "0.23.0"
bitcoin_hashes = { version = "0.7.6", features = [ "serde" ] }
bitcoincore-rpc = "0.11.0"
chrono = { version = "0.4.11", default-features = false }
dotenv = "0.15.0"
dirs = "3.0.0"
hex = "0.4.2"
serde = { version = "1.0.113", features = [ "derive" ] }
serde_json = "1.0.55"
lazy_static = "1.4.0"
anyhow = "1.0.31"
log = "0.4.8"
pretty_env_logger = "0.4.0"
structopt = "0.3.15"
thiserror = "1.0.20"

tokio = { version = "0.2.20", features = ["macros"], optional = true }
warp = { version = "0.2.3", optional = true }
async-std = { version = "1.6.2", optional = true }
reqwest = { version = "0.10.6", optional = true, features = ["json", "blocking"] }
