[package]
name = "pxt"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[features]
default = [ "electrum" ]
electrum = [  ]

[dependencies]
bitcoin = "0.18"
bitcoincore-rpc = { version = "0.6" }
bitcoin_hashes = { version = "0.3", features = [ "serde" ] }
chrono = "0.4.6"
dirs = "2.0.1"
secp256k1 = "0.12.2"
hex = "0.3.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.3"
failure = "0.1"
log = "0.4"
stderrlog = "0.4"
structopt = "0.2.17"
