[package]
name = "bwt"
version = "0.1.0"
description = "a lightweight wallet xpub tracker and query engine for Bitcoin"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/shesek/bwt"
repository = "https://github.com/shesek/bwt"
keywords = [ "bitcoin", "wallet tracker", "electrum", "xpub" ]
edition = "2018"
include = [ "src", "LICENSE" ]

[features]
default = [ "electrum", "http", "track-spends" ]
electrum = []
http = [ "warp", "tokio", "async-std" ]
webhooks = [ "reqwest" ]
track-spends = []

[dependencies]
bitcoin = "0.23.0"
bitcoincore-rpc = { version = "0.10.0" }
bitcoin_hashes = { version = "0.7.6", features = [ "serde" ] }
chrono = "0.4.11"
dotenv = "0.15.0"
dirs = "2.0.2"
secp256k1 = "0.17.2"
hex = "0.4.2"
serde = { version = "1.0.106", features = [ "derive" ] }
serde_json = "1.0.52"
serde_derive = "1.0.106"
lazy_static = "1.4.0"
failure = "0.1.8"
log = "0.4.8"
pretty_env_logger = "0.4.0"
structopt = "0.3.13"

tokio = { version = "0.2.20", features = ["macros"], optional = true }
warp = { version = "0.2.2", optional = true }
async-std = { version = "1.5.0", optional = true }
reqwest = { version = "0.10.4", optional = true, features = ["json", "blocking"] }

[patch.crates-io]
bitcoincore-rpc = { git = "https://github.com/shesek/rust-bitcoincore-rpc" }
